# Generated by Django 2.0.1 on 2018-01-05 19:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_re', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Образование'),
        ),
    ]
