# Generated by Django 2.0.1 on 2018-01-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_re', '0002_hobie'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobieUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hobie',
            name='user',
        ),
        migrations.AddField(
            model_name='hobieuser',
            name='hobie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_re.Hobie'),
        ),
        migrations.AddField(
            model_name='hobieuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_re.Profile'),
        ),
    ]
