# Generated by Django 2.0.1 on 2018-01-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_re', '0003_auto_20180105_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobieuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_re.Profile'),
        ),
    ]
