# Generated by Django 2.0.1 on 2018-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20180126_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rate_per_hour',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
