# Generated by Django 2.0.1 on 2018-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_project_rate_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rate_per_hour',
        ),
        migrations.AddField(
            model_name='module',
            name='rate_per_hour',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
