# Generated by Django 2.0.1 on 2018-02-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_auto_20180126_1537'),
        ('pm', '0007_auto_20180214_1344'),
    ]

    operations = [
    ]
