# Generated by Django 2.0.1 on 2018-02-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_auto_20180214_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
