# Generated by Django 2.0.1 on 2018-02-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_merge_20180214_1428'),
        ('pm', '0008_task_is_done'),
    ]

    operations = [
    ]
