# Generated by Django 2.0.1 on 2018-01-05 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills_re', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('level', models.CharField(blank=True, choices=[('level_1', 'level_1'), ('level_2', 'level_2'), ('level_3', 'level_3'), ('level_4', 'level_4'), ('level_5', 'level_5'), ('level_6', 'level_6'), ('level_7', 'level_7'), ('level_8', 'level_84'), ('level_9', 'level_9'), ('level_10', 'level_10')], max_length=255, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_re.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
