# Generated by Django 2.0.1 on 2018-01-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills_re', '0002_skilllevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_re.Profile'),
        ),
    ]
