# Generated by Django 2.0.1 on 2018-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_re', '0003_auto_20180105_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'level_1'), ('2', 'level_2'), ('3', 'level_3'), ('4', 'level_4'), ('5', 'level_5'), ('6', 'level_6'), ('7', 'level_7'), ('8', 'level_8'), ('9', 'level_9'), ('10', 'level_10')], max_length=255, null=True),
        ),
    ]
